name: Deploy GitHub Pages

on:
  push:
    branches:
      - main

# Allow only one concurrent deployment
concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5.6.0
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: pip install "mkdocs-material>=9.5,<10" "mkdocs-glightbox>=0.4,<1"

      - name: Build site
        run: mkdocs build --config-file mkdocs/mkdocs.yml

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: /tmp/mkdocs_site

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
